server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /hackathon

spring:
  main:
    banner-mode: off
  application:
    name: loan-process-ms
  cloud:
    kubernetes:
      enabled: true

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      accept-float-as-int: false

  datasource:
    url: ${FLEXCUBE_DB_URL:jdbc:postgresql://localhost:5432/test}
    username: ${FLEXCUBE_DB_USERNAME:postgres}
    password: ${FLEXCUBE_DB_PASSWORD:hidden}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle10gDialect

  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:/liquibase/changelog-master.yml
    drop-first: false
    database-change-log-table: MS_HACKATHON_DBCHANGELOG
    database-change-log-lock-table: MS_HACKATHON_DBCHANGELOGLOCK


